askpupkin/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('ask.views',
    url(r'^$', 'index_latest', name='index_latest'),
    url(r'^new/$', 'index_latest', name='index_latest'),
    url(r'^popular/$', 'index_popular', name='index_popular'),
    url(r'^question/$', 'answers', name='answers'),
    url(r'^tag/$', 'tag', name='tag'),
    url(r'^user/$', 'user', name='user'),
    url(r'^search/$', 'search', name='search'),
    url(r'^rating/$', 'rating', name='rating'),
    url(r'^mark/$', 'mark', name='mark'),
    url(r'^register/$', 'register', name='register'),
    url(r'^statistics/$', 'statistics', name='statistics'),
    url(r'^chart/$', 'chart', name='chart'),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += patterns('',
    url(r'^login/$', 'django.contrib.auth.views.login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout'),
)

ask/models.py
from django.db import models
from django.contrib.auth.models import User
from djangosphinx.models import SphinxSearch


class Tag(models.Model):
    name = models.CharField(max_length=32, db_index=True)

    def __unicode__(self):
        return self.name


class Question(models.Model):
    title = models.CharField(max_length=100)
    content = models.CharField(max_length=2048)
    author = models.ForeignKey(User)
    date = models.DateTimeField()

    tags = models.ManyToManyField(Tag)
    rating = models.IntegerField()
    search = SphinxSearch(
        index='questions',
        weights={
            'title': 100,
            'content': 40,
        }
    )

    def __unicode__(self):
        return self.title


class Answer(models.Model):
    content = models.CharField(max_length=1024)
    question = models.ForeignKey(Question)
    author = models.ForeignKey(User)
    date = models.DateTimeField()
    right = models.BooleanField()
    rating = models.IntegerField()
    search = SphinxSearch(
        index='answers',
        weights={
            'content': 100,
        }
    )

    def __unicode__(self):
        return self.content


class QuestionVote(models.Model):
    question = models.ForeignKey(Question)
    user = models.ForeignKey(User)
    value = models.SmallIntegerField()


class AnswerVote(models.Model):
    answer = models.ForeignKey(Answer)
    user = models.ForeignKey(User)
    value = models.SmallIntegerField()

ask/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms import *
from ask.models import Question
from django import forms
from ask.models import *


class TagsField(forms.CharField):
    def to_python(self, value):
        # Return an empty list if no input was given.
        if not value:
            return []
        tags = value.split(',')

        cleaned_tags = []

        for tag in tags:
            tag_name = tag.strip()
            if tag_name != '':
                if not cleaned_tags.__contains__(tag_name):
                    cleaned_tags.append(tag_name)

        return cleaned_tags

    def validate(self, value):
        # Use the parent's handling of required fields, etc.
        super(TagsField, self).validate(value)

        if len(value) > 3:
            raise forms.ValidationError("Should be 0-3 tags in here")


class QuestionForm(forms.Form):
    title = forms.CharField(max_length=100, widget=TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'What\'s your problem?'
    }))
    content = forms.CharField(max_length=2048, widget=Textarea(attrs={
        'class': 'form-control',
        'placeholder': 'Place detailed information here...'
    }))
    tags = TagsField(required=False, widget=TextInput( attrs={
        'class': 'form-control',
        'placeholder': 'tag1, tag2, tag3'
    }))


class AnswerForm(forms.Form):
    content = forms.CharField(max_length=1024, widget=Textarea(attrs={
        'id': 'id_answer_content',
        'class': 'form-control',
        'placeholder': 'Put your answer here...'
    }))


class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "email")

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

templates/answer.html
<div class="thumbnail answer" data-id="{{ answer.id }}"">
    <div class="row">
        <div class="col-md-1 rating">
            <a href="#" class="ratingArrow rating_up">
                <div class="glyphicon glyphicon-chevron-up"></div>
            </a>
            <div><b class="rating_value">{{ answer.rating }}</b></div>
            <a href="#" class="ratingArrow rating_down">
                <div class="glyphicon glyphicon-chevron-down"></div>
            </a>
        </div>
        <div class="col-md-11">
            <div class="answerContent">
                {% if answer.short_content %}
                {{ answer.short_content|linebreaks }}
                {% else %}
                {{ answer.content|linebreaks }}
                {% endif %}
            </div>
            <div class="answerFooter">
                <div class="asker_name pull-right"><b>Answered by:</b> <a href="/user/?name={{ answer.author.username }}">{{ answer.author.username }}</a></div><br>

                {% if user == question.author and page == 'answers' %}
                    {% if answer.right == False %}
                    <a class="mark">Mark as right</a>
                    {% else %}
                    <a class="mark">Right!</a>
                    {% endif %}
                {% endif %}

                {%  if answer.right and page == 'answers' and user != answer.author %}
                <b>Right!</b>
                {% elif page == 'search' %}
                <a href="/question/?q={{ answer.question_id }}">Go to question</a>
                {% endif %}
                <div class="qdate pull-right">{{ answer.date }}</div>
            </div>
        </div>
    </div>
</div>

templates/answers.html
{% extends "index.html" %}

{% block tabs %}
    <li><a href="/">New</a></li>
    <li><a href="/popular/">Popular</a></li>
    <li><a href="/statistics/">Statistics</a></li>
    <li class="active"><a>Question</a></li>
{% endblock %}

{% block content %}
    <div class="thumbnail" id="questions">
        <div class="thumbnail question" data-id="{{ question.id }}">
            <div class="row">
                <div class="col-md-1 rating">
                    <a href="#" class="ratingArrow rating_up">
                        <div class="glyphicon glyphicon-chevron-up"></div>
                    </a>
                    <div><b class="rating_value">{{ question.rating }}</b></div>
                    <a href="#" class="ratingArrow rating_down">
                        <div class="glyphicon glyphicon-chevron-down"></div>
                    </a>
                </div>
                <div class="col-md-11">
                    <div class="questionHeader">
                        <span class="qheader">{{ question.title }}</span>
                    </div>
                    <div class="questionContent">
                        {{ question.content|linebreaks }}
                    </div>
                    <div class="questionFooter">
                        <div class="asker_name pull-right"><b>Asked by:</b> <a href="/user/?name={{ question.author.username }}">{{ question.author.username }}</a></div><br>
                        <b>Tags:</b>
                        {% for tag in question.tags.all %}
                        <span><a href="/tag/?t={{ tag.name }}">{{ tag.name }}</a></span>
                        {% endfor %}
                        <div class="qdate pull-right">{{ question.date }}</div>
                    </div>
                </div>
            </div>
        </div>

        <hr>
        <div class="answers_title">Answers ({{ answers.count }}):</div>

        {% for answer in answers %}
            {% include 'answer.html' %}
        {% endfor %}

        {% if user.is_authenticated %}
        <div id="answerForm">
            <form method="POST" name="addQuestion" class="">
                {% csrf_token %}
                {{ answer_form.non_field_errors }}
                <div class="form-group">
                    <label for="id_answer_content" class="control-label your_answer">Your answer:</label>
                    {{ answer_form.content }}
                    <div class="row">
                        <div class="col-md-10">
                            {{ answer_form.content.errors }}
                        </div>
                        <div class="col-md-2" id="answer_footer">
                            <button class="btn btn-success" id="answer_button" type="submit">Answer!</button>
                        </div>
                    </div>
                </div>
                <input type="hidden" name="type" value="answer">
            </form>
        </div>
        {% else %}
            <div class="not_logged_to_answer">
                Please <a href="{% url 'django.contrib.auth.views.login' %}?next={{ request.get_full_path }}">log in</a> or
                <a href="/register/?next={{ request.get_full_path }}">register</a> to add your answer.
            </div>
        {% endif %}
    </div>
{%  endblock %}


{% block paginator %}
    <ul class="pagination">
        <li><a href="/{{ page }}/?q={{ question.id }}&page=1">&laquo;</a></li>
        {%  for i in page_range %}
            {%  if  i == page_id %}
            <li class="active"><a href="/{{ page }}/?q={{ question.id }}&page={{ i }}">{{ i }}</a></li>
            {% else %}
            <li><a href="/{{ page }}/?q={{ question.id }}&page={{ i }}">{{ i }}</a></li>
            {%  endif %}
        {%  endfor %}
        <li><a href="/{{ page }}/?q={{ question.id }}&page={{ pages_count }}">&raquo;</a></li>
    </ul>
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html>
<head>
    <title>Be smart - Ask Pupkin</title>
    <link rel="stylesheet" type="text/css" href="/static/css/index.css">
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap-theme.css">
	<link rel="stylesheet" type="text/css" href="/static/css/jquery.toast.min.css" />
    {% if request.path == '/logout/' %}
    <meta http-equiv="refresh" content="1; url=/">
    {% endif %}
</head>
<body>
    <header>

    </header>

    <div class="container">
        <div class="row" id="header">
            <div id="logo" class="col-md-10">
                <h2>Be smart - Ask Pupkin</h2>
            </div>
            <div class="col-md-2" id="headerRight">
                {% if user.is_authenticated %}
                Welcome, <a href="/user/?name={{ user.username }}">{{ user.username }}</a> (<a href="{% url 'django.contrib.auth.views.logout' %}">logout</a>)
                {% else %}
                <a href="{% url 'django.contrib.auth.views.login' %}?next={{ request.get_full_path }}">login</a> or
                <a href="/register/?next={{ request.get_full_path }}">register</a>
                {% endif %}
            </div>
        </div>

        <div class="row" id="content">
            <div class="col-md-9" id="leftCol">
                <ul class="nav nav-tabs" id="tabs">
                    {% block tabs %}{% endblock %}
                    {% if user.is_authenticated %}
                    <span id="ask" class="pull-right">
                        <a data-toggle="modal" href="#myModal" id="askLink">ASK!</a>
                    </span>
                    {% endif %}
                </ul>

                {% if page == 'user' %}
                    {% block usertabs %}{% endblock %}
                {% elif page == 'search' %}
                    {% block searchtabs %}{% endblock %}
                {% endif %}

                <div class="row">
                    {% block content %}{% endblock %}
                </div>
            </div>

            <div class="col-md-3" id="rightCol">
                <form id="search-form" method="GET" action="/search/">
                    <div class="input-group" id="searchBox">
                        <input id="search-query" type="text" name="query" class="form-control" placeholder="Search...">
                        <span class="input-group-btn">
                            <button id="search-button" class="btn btn-default" type="submit">
                                <i class="glyphicon glyphicon-search"></i>
                            </button>
                        </span>
                    </div>
                </form>

                <div class="panel panel-default">
                    <div class="panel-heading">Tags cloud</div>
                    <div class="panel-body" id="tagCloud">
                        {% for name, weight in popular_tags.iteritems %}
                        <a href="/tag/?t={{ name }}" class="tw{{ weight }}">{{ name }}</a>
                        {% empty %}
                        <div class="empty_list">No tags created so far</div>
                        {% endfor %}
                    </div>
                </div>

                <div class="panel panel-default">
                    <div class="panel-heading">Last registered</div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-6">
                                <ul class="lastRegisteredList">
                                    {% for user_name in last_registered_left %}
                                    <li><a href="/user/?name={{ user_name }}">{{ user_name }}</a></li>
                                    {% endfor %}
                                </ul>
                            </div>
                            <div class="col-md-6">
                                <ul class="lastRegisteredList">
                                    {% for user_name in last_registered_right %}
                                    <li><a href="/user/?name={{ user_name }}">{{ user_name }}</a></li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>

                <div id="lastRegistered">

                </div>
            </div>
        </div>

        <footer class="text-center">
            {% block paginator %}{% endblock %}
        </footer>

        {% if user.is_authenticated %}
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title">Ask here!</h4>
                    </div>
                    <form method="POST" name="addQuestion" class="form-horizontal">
                        {% csrf_token %}
                        <div class="modal-body">
                            {{ question_form.non_field_errors }}
                            <div class="form-group">
                                {{ question_form.title.errors }}
                                <label for="id_title" class="col-lg-2 control-label">Title:</label>
                                <div class="col-lg-10">
                                {{ question_form.title }}
                                </div>
                            </div>
                            <div class="form-group">
                                {{ question_form.content.errors }}
                                <label for="id_tags" class="col-lg-2 control-label">Question:</label>
                                <div class="col-lg-10">
                                {{ question_form.content }}
                                </div>
                            </div>
                            <div class="form-group">
                                {{ question_form.tags.errors }}
                                <label for="id_title" class="col-lg-2 control-label">Tags:</label>
                                <div class="col-lg-10">
                                {{ question_form.tags }}
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="submit" class="btn btn-primary">ASK!</button>
                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                        </div>
                        <input type="hidden" name="type" value="question">
                    </form>
                </div>
            </div>
        </div>
        {% endif %}
    </div>

    <script src="/static/js/jquery.js"></script>
    <script src="/static/js/bootstrap.js"></script>
    <script src="/static/js/index.js"></script>
    <script type="text/javascript" src="/static/js/jquery.toast.min.js"></script>
    {% block scripts %}{% endblock %}

    <script>
        jQuery(document).ready(function($) {
            $.toast.config.align = 'right';
            $.toast.config.width = 400;
        });
    </script>

    {% if question_form_failed == True %}
    <script>
        jQuery(document).ready(function($) {
            $('#myModal').modal()
        });
    </script>
    {% elif answer_form_failed == True %}
    <script>
        jQuery(document).ready(function($) {
            window.location.href += '#answerForm';
        });
    </script>
    {% endif %}
</body>
</html>

templates/question.html
 <div class="thumbnail question" data-id="{{ question.id }}">
    <div class="row">
        <div class="col-md-1 rating">
            <a href="#" class="ratingArrow rating_up">
                <div class="glyphicon glyphicon-chevron-up"></div>
            </a>
            <div><b class="rating_value">{{ question.rating }}</b></div>
            <a href="#" class="ratingArrow rating_down">
                <div class="glyphicon glyphicon-chevron-down"></div>
            </a>
        </div>
        <div class="col-md-11">
            <div class="questionHeader">
                <span class="qheader">{{ question.title }}</span>
            </div>
            <div class="questionContent">
                {{ question.short_content|linebreaks }}
            </div>
            <div class="questionFooter">
                <a href="/question/?q={{ question.id }}">Read answers ({{ question.answer_set.count }})</a> |
                <a href="/question/?q={{ question.id }}#answerForm">Answer</a>

                <span class="qdate pull-right">{{ question.date }}</span>
            </div>
        </div>
    </div>
</div>

templates/questions.html
{% extends "index.html" %}

{% block tabs %}
    {% if page == 'popular' %}
        <li><a href="/">New</a></li>
        <li class="active"><a>Popular</a></li>
        <li><a href="/statistics/">Statistics</a></li>
    {% elif page == 'new' %}
        <li class="active"><a>New</a></li>
        <li><a href="/popular/">Popular</a></li>
        <li><a href="/statistics/">Statistics</a></li>
    {% elif page == 'tag' %}
        <li><a href="/">New</a></li>
        <li><a href="/popular/">Popular</a></li>
        <li><a href="/statistics/">Statistics</a></li>
        <li class="active"><a>Tag: {{ tag }} ({{ questions_count }})</a></li>
    {% elif page == 'search' %}
        <li><a href="/">New</a></li>
        <li><a href="/popular/">Popular</a></li>
        <li><a href="/statistics/">Statistics</a></li>
        <li class="active"><a>Search: {{ search }} ({{ results_count }})</a></li>
    {% elif page == 'statistics' %}
        <li><a href="/">New</a></li>
        <li><a>Popular</a></li>
        <li class="active"><a>Statistics</a></li>
    {% endif %}
{% endblock %}

{% block content %}
    <div class="thumbnail" id="questions">
        {% for question in questions %}
            {% include "question.html" %}
            {% empty %}
            <div class="empty_list">No questions found. :(</div>
        {% endfor %}
    </div>
{%  endblock %}

{% block paginator %}
    <ul class="pagination">
    {% if page == 'tag' %}
        <li><a href="/{{ page }}/?t={{ tag.name }}&page=1">&laquo;</a></li>
        {%  for i in page_range %}
            {%  if  i == page_id %}
            <li class="active"><a>{{ i }}</a></li>
            {% else %}
            <li><a href="/{{ page }}/?t={{ tag }}&page={{ i }}">{{ i }}</a></li>
            {%  endif %}
        {%  endfor %}
        <li><a href="/{{ page }}/?t={{ tag }}&page={{ pages_count }}">&raquo;</a></li>
    {% else %}
        <li><a href="/{{ page }}/?page=1">&laquo;</a></li>
        {%  for i in page_range %}
            {%  if  i == page_id %}
            <li class="active"><a>{{ i }}</a></li>
            {% else %}
            <li><a href="/{{ page }}/?page={{ i }}">{{ i }}</a></li>
            {%  endif %}
        {%  endfor %}
        <li><a href="/{{ page }}/?page={{ pages_count }}">&raquo;</a></li>
    {% endif %}
    </ul>
{% endblock %}

templates/search.html
{% extends "index.html" %}

{% block tabs %}
    <li><a href="/">New</a></li>
    <li><a href="/popular/">Popular</a></li>
    <li><a href="/statistics/">Statistics</a></li>
    <li class="active"><a>Search: {{ query }}</a></li>
{% endblock %}

{% block searchtabs %}
    <ul class="nav nav-tabs nav-justified" id="tabs">
        {% if tab == 'questions' %}
            <li class="active"><a href="/search/?tab=questions&query={{ query }}">Questions ({{ questions_count }})</a></li>
            <li><a href="/search/?tab=answers&query={{ query }}">Answers ({{ answers_count }})</a></li>
        {% else %}
            <li><a href="/search/?tab=questions&query={{ query }}">Questions ({{ questions_count }})</a></li>
            <li class="active"><a href="/search/?tab=answers&query={{ query }}">Answers ({{ entries_count }})</a></li>
        {% endif %}
    </ul>
{% endblock %}

{% block content %}
    <div class="thumbnail" id="questions">
    {% if tab == 'questions' %}
        {% for question in entries %}
            {% include "question.html" %}
            {% empty %}
            <div class="empty_list">No questions match that query.</div>
        {% endfor %}
    {% elif tab == 'answers' %}
        {% for answer in entries %}
            {% include "answer.html" %}
            {% empty %}
            <div class="empty_list">No answers match that query.</div>
        {% endfor %}
    {% endif %}
    </div>
{% endblock %}

{% block paginator %}
    <ul class="pagination">
        <li><a href="/{{ page }}/?query={{ query }}&tab={{ tab }}&page=1">&laquo;</a></li>
        {%  for i in page_range %}
            {%  if  i == page_id %}
            <li class="active"><a>{{ i }}</a></li>
            {% else %}
            <li><a href="/{{ page }}/?query={{ query }}&tab={{ tab }}&page={{ i }}">{{ i }}</a></li>
            {%  endif %}
        {%  endfor %}
        <li><a href="/{{ page }}/?query={{ query }}&tab={{ tab }}&page={{ pages_count }}">&raquo;</a></li>
    </ul>
{% endblock %}

templates/statistics.html
{% extends "index.html" %}

{% block tabs %}
    <li><a href="/">New</a></li>
    <li><a href="/popular/">Popular</a></li>
    <li class="active"><a href="/statistics/">Statistics</a></li>
{% endblock %}

{% block content %}
    <h3>Polling dynamic chart:</h3>
    <div id="chart_div"></div>

    <h3>Long-polling ProgressBar:</h3>
    <div class="progress progress-striped active">
        <div class="progress-bar"  role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%">
        </div>
        <span id="progressCaption">0%</span>
    </div>
{% endblock %}

{% block scripts %}
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script src="/static/js/statistics.js"></script>
{% endblock %}

templates/user.html
{% extends "index.html" %}

{% block tabs %}
    <li><a href="/">New</a></li>
    <li><a href="/popular/">Popular</a></li>
    <li class="active"><a>User: {{ user_info.username }}</a></li>
{% endblock %}

{% block usertabs %}
    <ul class="nav nav-tabs nav-justified" id="tabs">
        {% if tab == 'info' %}
            <li class="active"><a href="/user/?tab=info&name={{ user_info.username }}">Info</a></li>
            <li><a href="/user/?tab=asked&name={{ user_info.username }}">Asked questions ({{ asked_questions_count }})</a></li>
            <li><a href="/user/?tab=answered&name={{ user_info.username }}">Answered questions ({{ answered_questions_count }})</a></li>
        {% elif tab == 'asked' %}
            <li><a href="/user/?tab=info&name={{ user_info.username }}">Info</a></li>
            <li class="active"><a href="/user/?tab=asked&name={{ user_info.username }}">Asked questions ({{ asked_questions_count }})</a></li>
            <li><a href="/user/?tab=answered&name={{ user_info.username }}">Answered questions ({{ answered_questions_count }})</a></li>
        {% elif tab == 'answered' %}
            <li><a href="/user/?tab=info&name={{ user_info.username }}">Info</a></li>
            <li><a href="/user/?tab=asked&name={{ user_info.username }}">Asked questions ({{ asked_questions_count }})</a></li>
            <li class="active"><a href="/user/?tab=answered&name={{ user_info.username }}">Answered questions ({{ answered_questions_count }})</a></li>
        {% endif %}
    </ul>
{% endblock %}

{% block content %}
    {% if tab == 'info' %}
        <div class="thumbnail" id="questions">
            <table class="table table-striped" id="user_info_table">
                <tr>
                    <td>Username: </td>
                    <td>{{ user_info.username }}</td>
                </tr>
                <tr>
                    <td>Full name: </td>
                    <td>{{ user_info.get_full_name }}</td>
                </tr>
                <tr>
                    <td>Email: </td>
                    <td>{{ user_info.email }}</td>
                </tr>
                <tr>
                    <td>Last login: </td>
                    <td>{{ user_info.last_login }}</td>
                </tr>
                <tr>
                    <td>Date registered: </td>
                    <td>{{ user_info.date_joined }}</td>
                </tr>
            </table>
        </div>
    {% elif tab == 'asked' %}
        <div class="thumbnail" id="questions">
        {% for question in questions %}
            {% include "question.html" %}
            {% empty %}
            <div class="empty_list">No questions asked by {{ user_info.username }} so far.</div>
        {% endfor %}
        </div>
    {% elif tab == 'answered' %}
        <div class="thumbnail" id="questions">
        {% for question in questions %}
            {% include "question.html" %}
            {% empty %}
            <div class="empty_list">No questions answered by {{ user_info.username }} so far.</div>
        {% endfor %}
        </div>
    {% endif %}
{% endblock %}

{% block paginator %}
    <ul class="pagination">
    {% if page == 'tag' %}
        <li><a href="/{{ page }}/?t={{ tag.name }}&page=1">&laquo;</a></li>
        {%  for i in page_range %}
            {%  if  i == page_id %}
            <li class="active"><a>{{ i }}</a></li>
            {% else %}
            <li><a href="/{{ page }}/?t={{ tag }}&page={{ i }}">{{ i }}</a></li>
            {%  endif %}
        {%  endfor %}
        <li><a href="/{{ page }}/?t={{ tag }}&page={{ pages_count }}">&raquo;</a></li>
    {% else %}
        <li><a href="/{{ page }}/?page=1">&laquo;</a></li>
        {%  for i in page_range %}
            {%  if  i == page_id %}
            <li class="active"><a>{{ i }}</a></li>
            {% else %}
            <li><a href="/{{ page }}/?page={{ i }}">{{ i }}</a></li>
            {%  endif %}
        {%  endfor %}
        <li><a href="/{{ page }}/?page={{ pages_count }}">&raquo;</a></li>
    {% endif %}
    </ul>
{% endblock %}